### ISSUE TITLE
Check container errors and let it fail correctly

### ISSUE THREAD

**Issue by friend1ws** [otiai10/awsub#1]
Even when the program ends with errors, the awsub always says:
"All * tasks completed successfully!"

For example, in the awsub quickguide, this happens even when --aws-iam-instance-profile is not specified and problems in accessing S3 occur
> [PREPARE] &2> fatal error: Unable to locate credentials

awsub should check the error code for each task and should show whether each task ends correctly or not.

**Comment by otiai10** [comment]
Please let you know there are 2 types of errors.

1. Application (awsub) error
2. Container (workflow) error

I would separate this issue to 2 TODO issues. Thanks

**Comment by friend1ws** [comment]
Yes. maybe, we can list up more types of errors, and would like to discuss more on the  handling on each error.
