### ISSUE TITLE
Error when the file-names of script or task file include "_" 

### ISSUE THREAD

**Issue by friend1ws** [otiai10/awsub#3]
star_alignment_task02-NThhYjJi: failed to create machine: exit status 1: Error creating machine: Invalid hostname specified. Allowed hostname chars are: 0-9a-zA-Z . -

This should be automatically converted to a hyphen ("-").

**Comment by otiai10** [comment]
> This should be automatically converted to a hyphen ("-").

The valid characters for machines depends on which services you use (AWS in this case).
IMO, I'm not sure **converting always** is the best way.

But, because "awsub" only supports AWS for now, converting can be temporary solution.
Thanks for the comment 😉
