### ISSUE TITLE
Output logs are garbled again

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#35]
By using the following sources, this garbled is reproducible. Please, try running genomon_pipeline_cloud and output logs are garbled.

[installation]

    git clone https://github.com/ken0-1n/genomon_pipeline_cloud.git
    cd genomon_pipeline_cloud
    pip install . --upgrade

[run]

    genomon_pipeline_cloud dna example_conf/sample_awsub_dna.csv s3://kchiba-test-batch/genomon_cloud example_conf/param_dna_awsub.cfg

[output log]

    [genomon-qc-tasks-20180207-024034-70661400] &2> + catL /tmp/genomon-resource/_GRCh37/reference/bait/refGene.coding.exon.151207.bed
    [genomon-qc-tasks-20180207-024034-70661400] &2> + ・・ｱｹｵｷｶｰ
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ ｫ  ｭ・
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ ｫ 銓褞 ﾞﾀﾌ ｯ鈑ⅰ瀅鉑肄ｯﾟﾇﾒﾃ雉ｷｯ趺魲蟇粃鴟ｯ貮褓螳胥蓚鰀ｮ褸・ｮｱｵｱｲｰｷｮ粢・
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ ｫ
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ 韃砌褪ﾟ・ｰ
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ ｫ 褸 ｱｹｵｷｶｰ ｭ ｰ 
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ 蓊ﾟ・ｱｹｵｷｶｰ
    ﾛ鈑ⅰ瀅鉑ｭｲｰｱｸｰｲｰｷｭｰｲｴｰｳｴｭｷｰｶｶｱｴｰｰﾝ ｦｲｾ ｫ ・ｭｱｹｵｷｶｰﾌ ｯ

**Comment by ken0-1n** [comment]
cat /proc/version

    Linux version 4.4.0-1049-aws (buildd@lcy01-amd64-001) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018

**Comment by otiai10** [comment]
```
[genomon-qc-tasks-20180207-133840-20406901] &2> + catL /tmp/genomon-resource/_GRCh37/reference/bait/refGene.coding.exon.151207.bed
[DEBUG]	[43 32 2 0 0 0 0 0 0 3 99 97 116 2 0 0 0 0 0 0 76 32 47 116 109 112 47 103 101 110 111 109 111 110 45 114 101 115 111 117 114 99 101 47 95 71 82 67 104 51 55 47 114 101 102 101 114 101 110 99 101 47 98 97 105 116 47 114 101 102 71 101 110 101 46 99 111 100 105 110 103 46 101 120 111 110 46 49 53 49 50 48 55 46 98 101 100 2 0 0 0 0 0 0 1]
[genomon-qc-tasks-20180207-133840-20406901] &2> + total_l=195760
[DEBUG]	[43 32 2 0 0 0 0 0 0 14 116 111 116 97 108 95 108 61 49 57 53 55 54 48 2 0 0 0 0 0 0 1]
[genomon-qc-tasks-20180207-133840-20406901] &2> + wc -l
[DEBUG]	[43 32 2 0 0 0 0 0 0 2 119 99 2 0 0 0 0 0 0 3 32 45 108 2 0 0 0 0 0 0 1]
```

**Comment by otiai10** [comment]
concluded it seems to be a bug (or app specific problem) of terminal application e.g. **teraterm**. plz reopen this issue when it gets detected on other applications. thx.
