### ISSUE TITLE
Security Group Limit Exceeded

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#36]
The security group limit exceeded when launching many EC2 instances.

    Error creating machine: Error in driver during machine creation: SecurityGroupLimitExceeded: The maximum number of security groups for VPC 'vpc-3311ce57' has been reached.
    status code: 400, request id: b2de4bd5-7000-498b-9a3a-acf55af449e5

I think that it would be better to create one security group per one awsub execution, not one EC2 instance.

**Comment by otiai10** [comment]
- https://github.com/docker/machine/issues/4359
- https://github.com/docker/machine/pull/391
- https://github.com/docker/machine/issues/387
