### ISSUE TITLE
Unable to run docker-machine provisioning 

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#38]
I occasionally get this error when trying to execute awsub.

    sv-filt-tasks-ubuntu-20180213-03410812-mtk4yjrm: failed to create machine: exit status 1: Running pre-create checks...
    Creating machine...
    (sv-filt-tasks-ubuntu-20180213-03410812-mtk4yjrm) Launching instance...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Provisioning with ubuntu(systemd)...
    Installing Docker...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Error creating machine: Error running provisioning: ssh command error:
    command : sudo systemctl -f start docker
    err     : exit status 1
    output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

    1 task(s) failed with errors
    Process Process-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python2.7/dist-packages/genomon_pipeline_cloud/batch_engine.py", line 60, in seq_execute
        subprocess.check_call(self.generate_commands(task, general_param))
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['awsub', '--aws-iam-instance-profile', 'testtest', '--verbose', '--debug-sleep', '2000', '--aws-ec2-instance-type', 't2.large', '--script', '/usr/local/lib/python2.7/dist-packages/genomon_pipeline_cloud/script/sv-filt.sh', '--image', 'genomon/sv_detection', '--tasks', '/home/ubuntu/tools/genomon_pipeline_cloud-0.1.0/tmp/sv-filt-tasks-ubuntu-20180213-034108.tsv']' returned non-zero exit status 1

**Comment by ken0-1n** [comment]
It will be reproduced less frequently than about once in 100 times.

**Comment by otiai10** [comment]
please reopen if you face this again
