### ISSUE TITLE
STAR test script is not working 

### ISSUE THREAD

**Issue by friend1ws** [otiai10/awsub#4]
awsub STAR test does not seem to work well currently.
When I perform the test script modyifing the paths of the output directory of task file, 
following message appears:

?download failed: s3://hgc-otiai10-test/examples/genomon_rna/db/GRCh37.STAR-2.5.2a/SA to tmp/GRCh37.STAR-2.5.2a/SA [Errno 28] No space left on device

and empty bam file is copied to the S3.

**Comment by friend1ws** [comment]
I thought this is related to the default storage size specified to EC2 by docker-machine. The document of docker-machine says the default size is 16GB for Amazon EC2. This is not sufficient for downloading STAR index files..

**Comment by otiai10** [comment]
ah, I'd add more options. thanks

**Comment by friend1ws** [comment]
But in that case, why awsub worked well at first? The storage size option is hard coded before and got deleted at some point?

**Comment by otiai10** [comment]
I suspect this commit https://github.com/otiai10/awsub/commit/b32db0c10b400d2f59697b2dab3622f77e5df806

**Comment by otiai10** [comment]
seems fixed. plz check https://github.com/otiai10/awsub/tree/master/test/star
@friend1ws
