### ISSUE TITLE
EC2 instance  failed to download Input file.

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#78]
I am trying to use v0.1.1 but program returned the following error
<details>
  <summary>error log</summary>
  <pre>
2018/05/08 13:38:09 [COMMAND]   Your tasks file is parsed and decoded to 2 job(s) ✅

2018/05/08 13:38:09 [COMMAND]   See logs here -> /Users/chibaken/days/180501/genomon/tools/genomon_pipeline_cloud/log/20180508_133809

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [CREATE]    Creating computing instance for this job...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [CREATE]    Creating computing instance for this job...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [CONSTRUCT] Constructing containers for this job...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [CONSTRUCT] Constructing workflow container inside the computing instance...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [CONSTRUCT] Constructing routine container inside the computing instance...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [CONSTRUCT] Constructing containers for this job...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [CONSTRUCT] Constructing workflow container inside the computing instance...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [CONSTRUCT] Constructing routine container inside the computing instance...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> Either of INPUT or INPUT_RECURSIVE must be specified to invoke 'download.sh'

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.ann to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.ann

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.fai to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.fai

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.amb to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.amb

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/sample/exome/xxxx_tumor/sequence1.fastq to tmp/genomon-resource/sample/exome/xxxx_tumor/sequence1.fastq

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.genome_size to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.genome_size

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/sample/exome/xxxx_tumor/sequence2.fastq to tmp/genomon-resource/sample/exome/xxxx_tumor/sequence2.fastq

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37_noScaffold_noDecoy.interval_list to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37_noScaffold_noDecoy.interval_list

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.pac to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.pac

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.sa to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.sa

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.bwt to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.bwt

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 0]    [DESTROY]   Terminating computing instance for this job...

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> Either of INPUT or INPUT_RECURSIVE must be specified to invoke 'download.sh'

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.amb to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.amb

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.ann to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.ann

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.fai to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.fai

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/sample/exome/xxxx_control/sequence2.fastq to tmp/genomon-resource/sample/exome/xxxx_control/sequence2.fastq

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/sample/exome/xxxx_control/sequence1.fastq to tmp/genomon-resource/sample/exome/xxxx_control/sequence1.fastq

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.genome_size to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.genome_size

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37_noScaffold_noDecoy.interval_list to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37_noScaffold_noDecoy.interval_list

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.pac to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.pac

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> 

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.sa to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.sa

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [FETCH] &1> download: s3://genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.bwt to tmp/genomon-resource/_GRCh37/reference/GRCh37/GRCh37.fa.bwt

[bwa-alignment-tasks-chibaken-20180508-133803.tsv 1]    [DESTROY]   Terminating computing instance for this job...

2018/05/08 13:43:25 failed to download `` with status 1, please use --verbose option

Process Process-1:

Traceback (most recent call last):

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap

self.run()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run

self._target(*self._args, **self._kwargs)

  File "build/bdist.macosx-10.11-intel/egg/genomon_pipeline_cloud/batch_engine.py", line 85, in execute

subprocess.check_call(self.generate_commands(task, general_param))

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call

raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['awsub', '--aws-iam-instance-profile', 'awsubtest', '--verbose', '--aws-ec2-instance-type', 't2.xlarge', '--disk-size', '64', '--script', '/Users/chibaken/.python-eggs/genomon_pipeline_cloud-0.1.1-py2.7.egg-tmp/genomon_pipeline_cloud/script/bwa-alignment.sh', '--image', 'genomon/bwa_alignment:0.1.0', '--tasks', '/Users/chibaken/days/180501/genomon/tools/genomon_pipeline_cloud/tmp/bwa-alignment-tasks-chibaken-20180508-133803.tsv']' returned non-zero exit status 1
  </pre>
</details>

Do you have any advice?

**Comment by otiai10** [comment]
That is because

- v0.0.9 allowed task values to be empty string
    - c.f) https://github.com/otiai10/awsub/commit/e5d91e2c8f6727421dd9869f42f8878051604717
- v0.1.0~, in contrast, does NOT allow empty string

Related #25

It **should allow** empty string. Thank you for reporting. I'll fix it.
