### ISSUE TITLE
Potential conflict of downloaded input file names

### ISSUE THREAD

**Issue by friend1ws** [otiai10/awsub#8]
It seems that when the input files in the S3 are downloaded to /tmp directory,
the directory structure is removed and only base names are kept.
So, I think in the current settings, when a task needs multiple input files, 
and the base name of these input files are the same
(e.g., s3://input_seq_otiai10/sequence.txt, s3://input_seq_friend1ws/sequence.txt),
some conflicts will occur.

If my observation is true, I think the directory structure of the input file should be kept after downloading to VMs.

**Comment by otiai10** [comment]
Yes, you're right. It can be happened.

> he directory structure of the input file should be kept

gonna do it. thanks
