### ISSUE TITLE
Error creating machine in AWS Cloud9

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#97]
the word-count test returned the following error.

```
2018/07/05 02:28:11 max retry of creating machine exceeded: failed 4 times with last error: Error creating machine: Error in driver during machine creation: Error launching instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: pp6CfPzwjaqOeXXXX  status code: 403, request id: 86d2000f-60cb-49d7-bcf8-8c5f65450e3f
```

 I have successfully create ec2 instance using aws cli.  

```
aws ec2 run-instances \
  --image-id ami-db710fa3 \
  --count 1 --instance-type t2.micro \
  --key-name chibaken.xxxxxx \
  --security-group-ids sg-xxxxxx \
  --subnet-id subnet-73a86c14
```

It also succeeds in docker-machine.

```
docker-machine create --driver amazonec2 hogehoge
```

Any suggestion?

**Comment by otiai10** [comment]
- Please specify which credential you are using.
- Please specify which IAM policies the credential (or role) has.
- cf) https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#unauthorized-operation

**Comment by otiai10** [comment]
Another approach, just try

```
docker-machine create \
  --driver amazonec2 \
  --amazonec2-iam-instance-profile awsub-compute-2018-06-07 \
  hogehoge
```

to check if your credential has IAM policies which awsub requires.

**Comment by ken0-1n** [comment]
Hello. I needed to have permission to pass IAM roles to launch the EC2 instance on awsub. Now it works perfect.    
Thank you for your help.

**Comment by otiai10** [comment]
Thank you for sharing your problem, it helps someone who would have the same problem in the future.
